name: calendar_strip
description:
  Flutter Calendar strip widget with custom date and custom styling. Date range can also be set between 2 date to
  disable selection of irrevelant dates
version: 2.0.0
homepage: https://github.com/IronLad85/flutter_calendar_strip.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
